---
title: "FHWA Rural Speed Safety Project"
author: "Subasish Das"
date: "January 7, 2019"
output:
  html_document:
    theme: flatly
    highlight: haddock
    includes:
      in_header: include/in_header.html
      before_body: include/navbar.html
---

# Task 4: Analysis [Data Analysis and Modeling Links]
## **Washington**

### Rural Two-lane
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_R2_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_R2_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_R2_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_R2_ARIMA.html)

### Rural Multi-lane Undivided
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RMU_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RMU_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RMU_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RMU_ARIMA.html)

### Rural Multi-lane Divided
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RMD_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RMD_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RMD_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RMD_ARIMA.html)


### Rural Interstate
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RI_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RI_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RI_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/WA_RI_daily_ARIMA.html)

### Modeling
* [EDA](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html3a/WADataEDA.html)
* [Correlation Plots](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html3a/WA_VarCorr.html)
* [Reduced Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html3a/WAReducedModels.html)

## **Ohio**
### Rural Two-lane
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_R2_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_R2_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_R2_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_R2_ARIMA.html)

### Rural Multi-lane Undivided
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RMU_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RMU_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RMU_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RMU_ARIMA.html)

### Rural Multi-lane Divided
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RMD_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RMD_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RMD_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RMD_ARIMA.html)


### Rural Interstate
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RI_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RI_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RI_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/OH_RI_ARIMA.html)

### Modeling
* [EDA](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html3a/OHDataEda.html)
* [Correlation Plots](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html3a/OH_VarCorr.html)
* [Reduced Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html3a/OHReducedModels.html)



## **North Carolina**
### Rural Two-lane
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_R2_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_R2_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_R2_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_R2_ARIMA.html)

### Rural Multi-lane Undivided
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RMU_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RMU_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RMU_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RMU_ARIMA.html)

### Rural Multi-lane Divided
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RMD_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RMD_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RMD_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RMD_ARIMA.html)


### Rural Interstate
* [Missing Values and Speed Distribution](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RI_md.html)
* [Descriptive Statistics](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RI_desSTAT.html)
* [Crash-Speed Associations-- Dygraphs](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RI_dygraphs.html)
* [Time Series Models](https://subasish.github.io/pages/FHWA_Rural_Speed_T4_1/html2a/NC_RI_ARIMA.html)

